services:
  frontend:
    build: ./Web/Apache
    ports:
      - "8080:80"
    container_name: arcdpsreporter_frontend
      # configs:
      #   - httpd-config
    secrets:
      - server-certificate

  node:
    build: ./Web/Node
      # networks:
      #  - back-tier
    volumes:
      - reports:/etc/reports
      - logs:/etc/logs
        # ports:
        #    - "3000:3000"
    container_name: arcdpsreporter_node
    secrets:
      - user
      - password
    environment:
      - MYSQL_USER_FILE=/run/secrets/user
      - MYSQL_PASSWORD_FILE=/run/secrets/password

  backend:
    build: ./Database/MySQL
    volumes:
      - db-data:/etc/data
      - reports:/etc/reports
    container_name: arcdpsreporter_backend
    secrets:
      - root
      - user
      - password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root
      - MYSQL_USER_FILE=/run/secrets/user
      - MYSQL_PASSWORD_FILE=/run/secrets/password
    command: --default-authentication-plugin=mysql_native_password


  parser:
    build: ./Parsers/Elite Insights Parsers
    volumes: 
      - reports:/etc/reports
      - logs:/etc/logs
    container_name: arcdpsreporter_parser

volumes:
  reports:
    driver: local
  logs:
    driver: local
  db-data:
    driver: local

      # configs:
      #   httpd-config:
      #     external: true

secrets:
  server-certificate:
    external: true
  root:
    file: root.txt
    # external: true
  user:
    file: user.txt
    # external: true
  password:
    file: password.txt
    # external: true

      # networks:
      #   front-tier:
      #     driver: bridge
      #   back-tier: 
      #     driver: bridge
