# 
services:
  node:
    build: ./Web/Node
    container_name: arcdpsreporter_node
    secrets:
      - user
      - password
    environment:
      - MYSQL_USER_FILE=/run/secrets/user
      - MYSQL_PASSWORD_FILE=/run/secrets/password
    ports:
      - "3000:3000"
  backend:
    build: './Database/MySQL/Restores/test'
    container_name: arcdpsreporter_backend
    volumes:
      - db-data:/etc/data
    secrets:
      - root
      - user
      - password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root
      - MYSQL_USER_FILE=/run/secrets/user
      - MYSQL_PASSWORD_FILE=/run/secrets/password
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
volumes:
  db-data:
    driver: local
secrets:
  root:
    file: root.txt
  user:
    file: user.txt
  password:
    file: password.txt