services:
  frontend:
    build: ./Web/Apache
    networks:
      - front-tier
      - back-tier
    ports:
      - "8080:80"
    # configs:
    #   - httpd-config
    # secrets:
    #   - server-certificate

  node:
    build: ./Web/Node
    networks:
      - back-tier
    volumes:
      - reports:/etc/reports
      - logs:/etc/logs
    ports:
      - "3000:3000"
    container_name: arcdpsreporter_node

  backend:
    build: ./Database/MySQL
    volumes:
      - db-data:/etc/data
      - reports:/etc/reports
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASS: ''
      MYSQL_DATABASE: 'web'
    container_name: arcdpsreporter_backend

  parser:
    build: ./Parsers/Elite Insights Parsers
    volumes: 
      - reports:/etc/reports
      - logs:/etc/logs

volumes:
  reports:
    driver: local
  logs:
    driver: local
  db-data:
    driver: local

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  front-tier:
    driver: bridge
  back-tier: 
    driver: bridge