-- Note CREATE SCHEMA is a synonym for CREATE DATABASE in mysql
CREATE SCHEMA IF NOT EXISTS log;
CREATE SCHEMA IF NOT EXISTS smp;
CREATE SCHEMA IF NOT EXISTS rpt;
CREATE SCHEMA IF NOT EXISTS gw2;
CREATE SCHEMA IF NOT EXISTS web; 
CREATE SCHEMA IF NOT EXISTS rol; 