SELECT LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, COUNT(PLY.LOG_ACC_NA) AS GRP_CNT_NR, SUM(DPS.LOG_DMG_NR) / LOG.LOG_DUR_MS * 1000 AS AVG_DPS_NR
FROM rpt.ILOGELT_INSIGHTS LOG
INNER JOIN rpt.IRPTPLY_PLAYERS PLY
    ON LOG.LOG_SYS_NR = PLY.LOG_SYS_NR
INNER JOIN rpt.IRPTPLY_DPSTARGETS DPS
    ON PLY.LOG_SYS_NR = DPS.LOG_SYS_NR
    AND PLY.LOG_ACC_NA = DPS.LOG_ACC_NA
WHERE DPS.LOG_TGT_NR=0
  AND DPS.LOG_PHS_NR=0
GROUP BY LOG.LOG_SYS_NR, LOG.LOG_DUR_MS, PLY.LOG_GRP_NR
;

SELECT LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, BMAP.LOG_BUF_NA, SUM(BUF.LOG_BUF_UP) / COUNT(BUF.LOG_BUF_UP) AS AVG_BUF_UP
FROM rpt.ILOGELT_INSIGHTS LOG
INNER JOIN rpt.IRPTPLY_PLAYERS PLY
    ON LOG.LOG_SYS_NR = PLY.LOG_SYS_NR
INNER JOIN rpt.IRPTPLY_BUFUPTM BUF
    ON PLY.LOG_SYS_NR = BUF.LOG_SYS_NR
    AND PLY.LOG_ACC_NA = BUF.LOG_ACC_NA
INNER JOIN rpt.IRPTBUF_MAP BMAP
    ON BUF.LOG_SYS_NR = BMAP.LOG_SYS_NR
    AND BUF.LOG_BUF_ID = BMAP.LOG_BUF_ID
WHERE BUF.LOG_PHS_NR=0
  AND BUF.LOG_BUF_ID IN ('b30328', 'b740', 'b1187', 'b725')
GROUP BY LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, BMAP.LOG_BUF_NA
;

SELECT LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, BMAP.LOG_BUF_NA, SUM(BUF.LOG_BUF_GEN) / COUNT(BUF.LOG_BUF_GEN) AS AVG_BUF_GEN
FROM rpt.ILOGELT_INSIGHTS LOG
INNER JOIN rpt.IRPTPLY_PLAYERS PLY
    ON LOG.LOG_SYS_NR = PLY.LOG_SYS_NR
INNER JOIN rpt.IRPTPLY_GRPBUFF BUF
    ON PLY.LOG_SYS_NR = BUF.LOG_SYS_NR
    AND PLY.LOG_ACC_NA = BUF.LOG_ACC_NA
INNER JOIN rpt.IRPTBUF_MAP BMAP
    ON BUF.LOG_SYS_NR = BMAP.LOG_SYS_NR
    AND BUF.LOG_BUF_ID = BMAP.LOG_BUF_ID
WHERE BUF.LOG_PHS_NR=0
  AND BUF.LOG_BUF_ID IN ('b30328', 'b740', 'b1187', 'b725')
GROUP BY LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, BMAP.LOG_BUF_NA
;

SELECT LOG.LOG_SYS_NR, PLY.LOG_GRP_NR, MCH.LOG_MCH_NA, COUNT(MCH.LOG_TIM_NR) AS MCH_CNT_NR
FROM rpt.ILOGELT_INSIGHTS LOG
INNER JOIN rpt.IRPTPLY_PLAYERS PLY
    ON LOG.LOG_SYS_NR = PLY.LOG_SYS_NR
INNER JOIN rpt.IRPTMCH_DATA MCH
    ON PLY.LOG_SYS_NR = MCH.LOG_SYS_NR
    AND PLY.LOG_CHR_NA = MCH.LOG_ACT_NA
WHERE LOG.LOG_SYS_NR='cca352a8-c6ca-11ed-9706-0242c0a85002'
  AND MCH.LOG_MCH_NA IN ('Dead', 'Downed', 'Res')
GROUP BY LOG.LOG_SYS_NR, LOG.LOG_DUR_MS, PLY.LOG_GRP_NR, MCH.LOG_MCH_NA
;

CREATE TABLE IF NOT EXISTS rpt.TRPTSQD_SUMMARY (
    LOG_SUM_ID CHAR(40) -- SHA1(CONCAT(LOG_GRP_NR, LOG_CNT_NR))
    ,LOG_GRP_NR INT
    ,LOG_CNT_NR INT
);

/* SUM_TYP_NA
-- Unknown
-- DPS
-- Buff Uptime
-- Buff Gen
-- Mechanics
*/
CREATE TABLE IF NOT EXISTS rpt.TRPTTYP_SUMMARY (
    LOG_TYP_ID CHAR(40) -- SHA1(CONCAT(SUM_TYP_NA, TYP_NA))
    ,SUM_TYP_NA VARCHAR(20)
    ,TYP_NA VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS rpt.TRPTSUM_AVG (
    LOG_SYS_NR CHAR(36) -- Log ID
    ,LOG_SUM_ID CHAR(40) -- ID that maps to the subgroup
    ,LOG_TYP_ID CHAR(40) -- ID that maps to the stat/type
    ,LOG_AVG_NR FLOAT -- averaged value
):

CREATE TABLE IF NOT EXISTS rpt.TRPTSUM_CNT (
    LOG_SYS_NR CHAR(36) -- Log ID
    ,LOG_SUM_ID CHAR(40) -- ID that maps to the subgroup
    ,LOG_TYP_ID CHAR(40) -- ID that maps to the stat/type
    ,LOG_CNT_NR INT  -- counted
):

/*
CREATE TABLE IF NOT EXISTS rpt.TRPTDPS_SUMMARY (
	 LOG_SUM_ID CHAR(40)
    ,AVG_DPS_NR FLOAT
);

CREATE TABLE IF NOT EXISTS rpt.TRPTBUF_SUMMARY (
	 LOG_SUM_ID CHAR(40)
    ,LOG_BUF_ID CHAR(10) 
    ,AVG_BUF_UP FLOAT
    ,AVG_BUF_GEN FLOAT 
);

CREATE TABLE IF NOT EXISTS rpt.TRPTMCH_SUMMARY (
	 LOG_SUM_ID CHAR(40)
    ,LOG_MCH_NA VARCHAR(256) CHARACTER SET utf8mb4 
    ,MCH_CNT_NR INT
);
*/