pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir './Web/Apache/Elm'
                    args '-u root --privileged'
                }
            }
            steps {
                sh 'cd ./Web/Apache/Elm && elm make ./src/Main.elm --optimize --output=main.js'
                sh 'uglifyjs --output ./Web/Apache/Elm/main.min.js --compress --mangle -- ./Web/Apache/Elm/main.js'
                // archiveArtifacts artifacts: 'main.min.js'
            }
        }
        stage('Deploy') {
            agent any
            environment {
                GIT_CREDS = credentials('git-token')
            }
            steps {
                sh 'git add ./Web/Apache/Elm/main.min.js'
                sh 'git commit -m "Jenkins Build"'
                sh ('git push https://$GIT_CREDS@github.com/KRNelson/arcdpsReporter')
            }
        }
    }
}