pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir './Web/Apache/Elm'
            args '-u root --privileged'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd ./Web/Apache/Elm && elm make ./src/Main.elm --optimize --output=main.js'
                sh 'uglifyjs --output main.min.js --compress --mangle -- ./Web/Apache/Elm/main.js'
                archiveArtifacts artifacts: 'main.min.js'

                withCredentials([usernamePassword(credentialsId: '8e125cbe-0307-46f1-b94e-7f09e7ceacdd', passwordVariable:'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh ("git tag -a some_tag -m 'Jenkins'")
                    sh ("git push https://${GIT_USERNAME}:${GIT_PASSWORD}@arcdpsReporter --tags")
                }
            }
        }
    }
}