pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir './Web/Apache/Elm'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'whoami'
                sh 'cd ./Web/Apache/Elm && elm make ./src/Main.elm --optimize --output=main.js'
                sh 'uglifyjs --output main.min.js --compress --mangle -- ./Web/Apache/Elm/main.js'
            }
        }
    }
}