pipeline {
    agent {
        docker {
            image 'node'
            args '-p 3443:3443'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install -g elm@0.19.1'
                sh 'npm install -g uglify-js'
                sh 'cd ./Web/Apache/Elm && elm make ./src/Main.elm --optimize --output=main.js && uglifyjs --output main.min.js --compress --mangle -- main.js'
                sh 'ls -la'
            }
        }
    }
}