pipeline {
    agent {
        docker {
            image 'node:16.17.1-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
                sh 'npm install -g elm@0.19.1'
            }
        }
    }
}