-- Note DROP SCHEMA is a synonym for DROP DATABASE in mysql
DROP SCHEMA IF EXISTS rol;
DROP SCHEMA IF EXISTS web;
DROP SCHEMA IF EXISTS gw2;
DROP SCHEMA IF EXISTS rpt;
DROP SCHEMA IF EXISTS smp;
DROP SCHEMA IF EXISTS log;