-------------------------------------------------
-------------------------------------------------
DROP TABLE IF EXISTS rpt.IRPTJSON;

DROP TABLE IF EXISTS smp.ILOGVER_SIMPLEARCVERSION;
DROP TABLE IF EXISTS smp.ILOGSER_SERVERTIME;
DROP TABLE IF EXISTS smp.ILOGCBT_EVENTS;
DROP TABLE IF EXISTS smp.TLOGCBT_LANGUAGE;
DROP TABLE IF EXISTS smp.TLOGCBT_CUSTOMSKILL;
DROP TABLE IF EXISTS smp.TLOGCBT_BUFFREMOVE;
DROP TABLE IF EXISTS smp.TLOGCBT_STATECHANGE;
DROP TABLE IF EXISTS smp.TLOGCBT_ACTIVATION;
DROP TABLE IF EXISTS smp.TLOGCBT_RESULT;
DROP TABLE IF EXISTS smp.TLOGCBT_IFF;
DROP TABLE IF EXISTS smp.ILOGPLY_PLAYERS;
DROP TABLE IF EXISTS smp.ILOGLOC_LOCALTIME;
DROP TABLE IF EXISTS smp.ILOGHED_HEADER;
DROP TABLE IF EXISTS smp.ILOGBOS_BOSS;

DROP TABLE IF EXISTS log.TLOGMAT_BRIDGE;
DROP TABLE IF EXISTS log.TLOGFIL;
DROP TABLE IF EXISTS log.TLOGCAT;