pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    filename 'build.Dockerfile'
                    dir './Web/Node'
                    args '-u root --privileged'
                }
            }
            steps {
                sh 'cd ./Web/Node && npm install package.json && tsc --project tsconfig.json'
                sh 'uglifyjs --output ./Web/Node/build/express.min.js --compress --mangle -- ./Web/Node/build/express.js'
                archiveArtifacts artifacts: 'Web/Node/build/express.min.js'
            }
        }
        stage('Deploy') {
            agent any
            environment {
                GIT_CREDS = credentials('git-token')
            }
            steps {
                sh 'git status -uno'
                // sh 'git add ./Web/Node/build/express.min.js'
                // sh 'git commit -m "Jenkins Controller Build" -uno --allow-empty'
                // sh ('git push https://$GIT_CREDS@github.com/KRNelson/arcdpsReporter')
            }
        }
    }
}